# Generated by Django 4.1.9 on 2023-05-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='')),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(max_length=15)),
                ('instegram_link', models.CharField(max_length=150)),
                ('facebook_link', models.CharField(max_length=150)),
            ],
        ),
    ]
