# Generated by Django 4.1.9 on 2023-05-13 16:24

import custom_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='logo',
            field=models.ImageField(storage=custom_storage.CustomImageStorage(), upload_to=''),
        ),
    ]
