# Generated by Django 4.1.9 on 2023-05-14 12:10

import custom_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(storage=custom_storage.CustomImageStorage(), upload_to='')),
            ],
        ),
    ]
