# Generated by Django 4.1.9 on 2023-05-13 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_image', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_image',
            name='insert_date',
        ),
    ]
