# Generated by Django 4.1.9 on 2023-05-13 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websites', '0002_alter_website_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_1', models.CharField(max_length=100)),
                ('phase_2', models.CharField(max_length=100)),
                ('phase_3', models.CharField(max_length=100)),
                ('phase_4', models.CharField(max_length=100)),
                ('website', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='websites.website')),
            ],
        ),
    ]
