# Generated by Django 4.1.9 on 2023-05-13 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_alter_website_logo'),
        ('phases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='website',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
    ]
