# Generated by Django 4.1.9 on 2023-05-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='phase_1_header',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phase',
            name='phase_2_header',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phase',
            name='phase_3_header',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phase',
            name='phase_4_header',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
